# Generated by Django 2.2.5 on 2020-06-04 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_auto_20200604_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='baths',
            new_name='bathrooms',
        ),
    ]
