# Generated by Django 2.2.5 on 2020-06-04 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_auto_20200604_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='house_rules',
            new_name='rules',
        ),
    ]
